$ANSIBLE_VAULT;1.1;AES256
39333236393539336666343939646232663030616433323762306532616265396431613565626431
6637343536383662633766313639303130313334353662330a306237613436373361323232303938
39326566656438616166386234373062616638616133653230613732303061356130633766356365
3131373837363734610a373332346232623938646262376330343332353735643131626238613865
36646336363233613863363162643539366539356236373532653661356134666339316139616434
61373033643035313030353336656638316430663835323061376230366335646430386237353635
34373261333962353162326635663039646637363233633261373062613766643236633764373332
33346535366136303663303636626138363834623738326561386531313566336534306233623861
38333962333137313739323839313433643236636434313166666437333737303266393537646664
39356564336431616139373533613430343831613262623531393039313932623163356562313964
31313832373166353061396530383361316131313938373137393035353761663438633337616639
36343065343066346663666166366339656363356164363063663031313831383831663865396364
33623630383630343430393430333736393161613337343166656363313362633339373965343165
34653537323266306139393639306638376332616337343231383862643465396535373832356230
34306630316534366230643339326134393934333039653265613836386461326435326561393066
34636266363531353136
