---
# handlers file for /home/ubuntu/project/roles/alb-switch
- name: slack_success
  community.general.slack:
    token: "{{ slack_token }}"
    msg: ":white_check_mark: {{ your_name }} Green versiyona başarıyla geçildi :rocket:"
    channel: "{{ slack_channel }}"
    username: "Ansible"
  delegate_to: localhost
  when: slack_enabled | default(true)


- name: slack_rollback
  community.general.slack:
    token: "{{ slack_token }}"
    msg: ":warning: {{ your_name }} Green versiyon başarısız oldu. Rollback ile Blue versiyona dönüldü :arrow_backward:"
    channel: "{{ slack_channel }}"
    username: "Ansible"
  delegate_to: localhost
  when: slack_enabled | default(true)
