---
# vars file for /home/ubuntu/project/roles/alb-switch
slack_enabled: true
region: "us-east-1"
phonebook_tg_green_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:targetgroup/phonebook-tg-green/18ebe071a5af53ae"
phonebook_tg_blue_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:targetgroup/phonebook-tg-blue/9e96c0e44bcced1b"
subnet_ids: "subnet-48b9b666"
security_group_id: "sg-0e79746a611f7ab76"
alb_listener_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:listener/app/phonebook-alb/8904d5290f50e3ac/639aab52e28bd29a"
slack_token: "{{ vault_slack_token }}"
slack_channel: "#ansible-project"
green_server_phonebook_ip: "3.94.173.118"
your_name: "DEVOPS-TEAM"